### ISSUE TITLE
zsh is now the default shell for Mac

### ISSUE THREAD

**Issue by AndKenneth** [dev-academy-programme/computer-setup#3]
The instructions ask for the user to install zsh, but since Catalina, ZSH has already been preinstalled and set as the default shell for macOS.

**Comment by kelly-keating** [comment]
Closing this issue as, by using brew to install over top of the default install, you will get a seperate version of zsh managed by homebrew that will be easier to update later, and many students are still on earlier (pre Catalina) OS versions, so good to keep in for now anyway.
