### ISSUE TITLE
Instructions for ARM Macs

### ISSUE THREAD

**Issue by AndKenneth** [dev-academy-programme/computer-setup#4]
**Still trying this out, looks good but I'll report on any issues**

Problem: Macs with the new apple sillicon processors often have bugs when running node. Newer versions of node sometimes fix these, but the curriculum uses v14, the LTS version of node. Problems between students running v14 and v15 include differences in the package lock file creating huge diffs between commits.

`arch` will print the current architecture - if the result is `arm64` these instructions will need to be used

`arch x86_64 zsh` will launch a shell that runs with the rosetta translation layer, allowing x64 binaries to automatically be translated at launch to arm64.

then run `nvm install --lts` in that same shell. Because it's running in a Rosetta shell, it will install the x64 binary of the LTS version of node. After that close that shell, and run your programs as normal.

Because the version of node and nvm installed now are running in a rosetta context, dependancies installed will also be those x64 versions.

If any updates are to be installed with nvm, using the shell started with `arch x86_64 zsh` will be necessary to get the x64 versions

**Comment by rossjourdain** [comment]
Thanks for the heads up!  I don't have one of the new ARM machines handy to play with so I'll keep this issue open as reference for now in case we have other students who see issues.

**Comment by meetjohngray** [comment]
Not sure if this is still relevant or not @gerardpaapu

**Comment by gerardpaapu** [comment]
I think this is no longer  problem with current LTS
